name: Daily Job Search Email

on:
  schedule:
    - cron: '0 6 * * *'  # 12 PM IST (6 AM UTC)
  workflow_dispatch:

jobs:
  search_and_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run job search
        run: python job_search_emailer.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
